### ISSUE TITLE
Sky stretching

### ISSUE THREAD

**Issue by nstlaurent** [Helion-Engine/Helion#410]
The sky is probably stretched a bit too much. Especially noticeable in eviternity where the moon cannot be seen. GZDoom does some stretching, but quite a bit less.
Helion:
![screenshot_Helion_eviternity](https://user-images.githubusercontent.com/42744211/129814621-1f0a4985-d8d2-468b-b985-2b1178fc7148.png)
GZDoom:
![screenshot_gzdoom_eviternity](https://user-images.githubusercontent.com/42744211/129814626-d40dc26e-a3a7-4db1-a78a-fa24e47d55ce.png)

**Comment by Calinou** [comment]
Sky stretching seems to be implemented as of https://github.com/Helion-Engine/Helion/commit/632a0fb93e62bb3eab9c48f8c9e7742c1cadeb05, although gaps are noticeable with FOV values higher than the default. Example with 120°, which exaggerates the issue:

![Screenshot_20240108_223659](https://github.com/Helion-Engine/Helion/assets/180032/1e30636a-f200-47ad-a9f5-264a1c4905f0)

On this particular spot, the lowest FOV where the issue is noticeable is 101° (on a 16:9 display).

Using mirrorred repeat for the repeated portion of the sky might help make the issue less noticeable.

**Comment by nstlaurent** [comment]
I see the problem. The sky rendering is still assuming 90 FOV. It wasn't updated to take the configurable FOV into account.

**Comment by nstlaurent** [comment]
Should be fixed with [45139af](https://github.com/Helion-Engine/Helion/commit/45139afec7bd0477fb0922bda8e8cf34c815de14)

**Comment by Calinou** [comment]
> Should be fixed with [45139af](https://github.com/Helion-Engine/Helion/commit/45139afec7bd0477fb0922bda8e8cf34c815de14)

Works great, thanks!

There's some visible tesselation in the sky with high resolutions if you look closely between the mountains:

![Screenshot_20240109_013524](https://github.com/Helion-Engine/Helion/assets/180032/dea54582-d2ab-4565-ad53-c45831a7251d)

See highlighted areas in red:

![Screenshot_20240109_013524a](https://github.com/Helion-Engine/Helion/assets/180032/383691f2-fcc5-4df6-9b2d-b2bd513bcf8f)

This can probably be fixed with a higher subdivision level for the sphere, which should only have a very small performance cost.

**Comment by nstlaurent** [comment]
This is a symptom of using nearest filtering. You would have to change to bilinear or trilinear. I also just noticed that changing the texture filtering in the menu doesn't update the sky until restart so I will need to fix that.

**Comment by Calinou** [comment]
> This is a symptom of using nearest filtering. You would have to change to bilinear or trilinear.

I don't mean the aliasing in the sky texture, but the lack of geometric detail on the sphere used to draw the sky. It's like the sky was drawn in a low-detail sphere where you can see its facets:

<img src="https://github.com/Helion-Engine/Helion/assets/180032/7509e636-8015-4470-a8e1-a6346bbe9f63" width="50%">

**Comment by nstlaurent** [comment]
It's using 32 points vertical and horizontal which generates 6,144 vertices. Doubling the point count just moves some of the noticeable points but you can still see them if you look. And doubling the point count explodes the vertex count to 24,576. I can see the same thing in GZDoom.
